---
#stabvest_deploy_dir_win: "C:\\stabvest"
#stabvest_deploy_dir_unix: "/stabvest"
#stabvest_task_create: false
#stabvest_task_name: "stabvest"
#stabvest_task_interval: 300 #seconds. cron needs this to be an even minutes value (so divisible by 60)
stabvest_agent_executable: "agent.py" 
stabvest_tester_executable: "agent_tester.py"
stabvest_include_tester: true
stabvest_service_start: true

stabvest_agent_name: "apache2"
stabvest_auth_token: "testtoken"
stabvest_server_url: "https://127.0.0.1:80/"
stabvest_server_timeout: 5
stabvest_sleeptime: 60
stabvest_disarm: false
stabvest_iptables_path: "iptables"

stabvest_ports:
  - 80
stabvest_services:
#  - "W3SVC"
  - "apache2"
#  - "httpd"
stabvest_packages:
#  - "IIS-WebServerRole"
  - "apache2"
#  - "httpd"
stabvest_service_backups:
  PathName: "C:\\\\Windows\\\\system32\\\\svchost.exe -k iissvcs"
  StartName: "localSystem"
  Dependencies: "['WAS','HTTP']"
  DisplayName: "World Wide Web Publishing Service"
  StartType: "Auto"
#stabvest_service_backups:
#  PathName: "C:\\Windows\\system32\\svchost.exe -k AxInstSVGroup"
#  StartName: "LocalSystem"
#  Dependencies: null
#  DisplayName: "ActiveX Installer (AxInstSV)"
#  StartType: "Manual"
stabvest_protected_folders: ["/var/www"]
#stabvest_protected_folders: ['C:\\inetpub\\wwwroot']
stabvest_debug_print: true
stabvest_backupdir: ""
stabvest_logfile: "log.txt"
stabvest_statusfile: "status.txt"
stabvest_mtu_min: 1200
stabvest_mtu_default: 1300
stabvest_mtu_max: 1514
stabvest_linux_default_ttl: 64
stabvest_agent_type: "stabvest"

#stabvest_deploy_dir: "C:\\stabvest\\{{ stabvest_agent_name }}\\"
stabvest_deploy_dir: "/stabvest/{{ stabvest_agent_name }}/"