---
# ansible-playbook stabvest_playbook.yaml -i inventory.yaml -t stabvest_server -vv
- name: Cleanup
  #hosts: ansible-controller
  hosts: active
  roles:
    - cleanup
  tags:
    - cleanup
    - full
    
- name: Deploy Stabvest Server
  hosts: ansible-controller
  roles:
    - stabvest_server
  tags:
    - stabvest
    - stabvest_server
    - owlet
    - owlet_server
    - full

- name: Deploy Stabvest Client
  #hosts: iis-winserv22
  hosts: testing-ubu24
  #hosts: testing-deb12
  #hosts: testing-centos8
  #hosts: testing-rocky9
  #hosts: testing-alpine
  roles:
    - stabvest_client
  tags:
    - stabvest
    - stabvest_client
    - full

- name: Deploy Owlet Client
  #hosts: iis-winserv22
  hosts: testing-ubu24
  #hosts: testing-deb12
  #hosts: testing-centos8
  #hosts: testing-rocky9
  #hosts: testing-alpine
  roles:
    - owlet
  tags:
    - owlet
    - owlet_client
    - full

- name: Deploy Stabvest Client Automated (do not touch)
  hosts: all
  roles:
    - stabvest_client
  tags:
    - stabvest_client_auto

- name: Deploy Owlet Client Automated (do not touch)
  hosts: all
  roles:
    - owlet
  tags:
    - owlet_auto