---
- name: Start Stabvest Service (Linux/Unix)
  service:
    name: "stabvest-{{ stabvest_agent_name if ansible_os_family != 'FreeBSD' else '_' + stabvest_agent_name }}"
    state: started
    enabled: yes
  when: ansible_os_family in ["RedHat", "Debian", "Alpine", "FreeBSD"]

- name: Start Stabvest Service (Windows)
  win_service:
    name: "stabvest-{{ stabvest_agent_name }}"
    start_mode: auto
    state: started
  when: ansible_os_family == "Windows"